Repository malleatus/nyx, pull requests merged in 2020-03, with the labels that each got.

#7 Implement `nyx report-failures` subcommand.
  .eslintrc.base.js
  .gitignore
  package.json
  src/commands/report-failure.ts
  src/index.ts
  yarn.lock
Labels: enhancement

#10 Add missing dependencies.
  package.json
  yarn.lock
Labels: bug

#9 Add eslint-plugin-node to linting configuration.
  .eslintrc.base.js
  package.json
  yarn.lock
Labels: internal

#14 Run tests against macOS, Ubuntu, and Windows in CI.
  .github/workflows/ci.yml
Labels: internal

#13 Avoid linting in `test` CI job.
  .github/workflows/ci.yml
Labels: internal

#12 Add `build:clean` script (and run it from `yarn build`).
  package.json
  yarn.lock
Labels: internal

#11 Rename from nyx.js -> @malleatus/nyx
  package.json
  src/commands/report-failure.ts
Labels: enhancement

#20 Prevent TypeScript from compiling down to ES5.
  tsconfig.json
Labels: bug

#19 Ensure async in report-failure is awaited.
  src/commands/report-failure.ts
Labels: bug

#22 Use @typescript-eslint/eslint-parser's recommended set of linting rules.
  .eslintrc.base.js
  src/commands/report-failure.ts
Labels: internal

#28 Add acceptance testing infrastructure with PollyJS.
  .eslintrc.base.js
  .recordings/basic-test_3799535060/recording.har
  jest.config.js
  package.json
  src/commands/report-failure.test.ts
  src/commands/report-failure.ts
  yarn.lock
Labels: internal

#29 Update prettier related packages to 2.0.
  package.json
  src/commands/report-failure.test.ts
  src/index.test.ts
  src/index.ts
  yarn.lock
Labels: internal

#41 Prevent `jest` from running tests twice upon `yarn test`.
  jest.config.js
Labels: internal

#40 Move development only types into top level `types/` folder.
  .eslintrc.base.js
  src/commands/report-failure.test.ts
  tsconfig.json
  types/@pollyjs/persister.d.ts
  types/@sinonjs/fake-timers.d.ts
Labels: internal

#43 Ensure eslint-plugin-node knows the final compiled paths.
  .eslintrc.base.js
  src/index.ts
Labels: internal

#49 Speed up linting and lint-staged.
  .eslintignore
  package.json
Labels: internal

#48 Migrate to using parsed arguments (instead of environment variables).
  src/commands/report-failure.test.ts
  src/commands/report-failure.ts
  src/index.ts
  src/utils/assert.ts
Labels: breaking, enhancement
